### ISSUE TITLE
[BUG] "bxt_cap_skip_non_gameplay_frames 1" crashes when demo(s) enqueued for playback

### ISSUE THREAD

**Issue by sykesjd** [YaLTeR/bxt-rs#93]
Bug found with latest bxt-rs-Windows-release artifact built off master

Reproduction steps:
1. Start game with bxt-rs injected (game itself doesn't appear to matter - originally found with GMC, but reproduced the issue in HL as well).
2. Execute command `bxt_cap_skip_non_gameplay_frames 1`.
3. Enqueue demo(s) for playback, either via `playdemo` or via `bxt_play_run`/`bxt_play_folder`.

Game crashes after freezing briefly on an ostensible OOB frame from the demo.

Same crash can be reproduced via `bxt_play_run`/`bxt_play_folder` then `bxt_cap_skip_non_gameplay_frames 1` during demo playback, but _not_ via `playdemo` on a single demo then `bxt_cap_skip_non_gameplay_frames 1` while it plays back, indicating the issue is with demos being queued to play rather than demos playing outright.

Note that `bxt_cap_start` does not need to be executed in order to reproduce the crash.

When using `bxt_play_run`/`bxt_play_folder`, bxt-rs.log shows DEBUG lines for demos being queued for playback, but nothing after that.

**Comment by khanghugo** [comment]
Thanks for the detailed report. I pushed out a fix #94 and it doesn't crash on my end (anymore).

**Comment by khanghugo** [comment]
Oh wow, I was trying to reproduce this earlier and I had crash. It had nothing to do with this apparently (probably Wayland Linux shenanigan). So, I cannot reproduce this error and the PR I just mentioned earlier MIGHT fix something, which I am positively believing that it will not fix anything.

I am testing on Linux and it showed no problem. However, when I test with WINE, it seems to crash when demo changes through `bxt_play_run`/`bxt_play_folder`. Maybe something totally unrelated.

That's my early report. Let me see what is really going on.

**Comment by khanghugo** [comment]
Maybe platform difference because I cannot reproduce it with your report through WINE. Though Counter-Strike 1.6 crashes even without injection so I guess I cannot fix this unless someone else can chip in.

Just to clarify why #94 exists again, I was trying reproduce this and I got crash (twice). So I came up with that fix and it doesn't crash. I then tried the non patched version and it doesn't crash. Very odd yes.

**Comment by sykesjd** [comment]
I tried the DLL produced for #94 and the issue went away. I then retried the DLL from latest master like you described and the issue came back, so #94 does indeed appear to fix the issue, at least on my end.

FWIW - my setup specifically is run with [wine32on64](https://github.com/Gcenx/homebrew-wine) on an M2 Mac, so I definitely would not be surprised if the issue were specific to my setup 🙃

**Comment by sykesjd** [comment]
Spoke too soon - the issue is indeed fixed as described, but now introducing `bxt_cap_start` into the process bring the crash back.

**Comment by khanghugo** [comment]
That is definitely odd. If possible, you can run the debug build and see if there is any backtrace from bxt-rs. The issue you are having is different now. For me, this works perfectly normal on my machine(s) (the one I was testing with has not been in used for weeks so I guess it could be why it crashed at first).

I am curious why you would run wine for the game. Is it possible for you to run the game natively? I could be possible that the game might work better that way since it barely works for me when I try Counter-Strike. Anyways, I assume you are running on legacy version? (pre anniversary)

**Comment by sykesjd** [comment]
Sorry, I think you'll have to clarify what you mean by 'backtrace' - I just downloaded the latest bxt-rs-Windows-debug artifact and injected that, then did `bxt_cap_skip_non_gameplay_frames 1`, `bxt_play_run`, then `bxt_cap_start`, but the bxt-rs.log produced doesn't show anything after the demos being queued for `bxt_play_run` even with the crash on the last command.

I specifically am running games from GoldSrc Package 2.4 rather than directly from Steam, so not using wine is not a possibility for me (nor is running _any_ GoldSrc game natively, since as I mentioned previously I'm on an M2 Mac).

I'll dump the bxt-rs.log output here in case you're able to glean something from it I can't:
```
2024-01-29T16:01:00.496961Z  INFO bxt_rs::utils: bxt-rs version 4.0-47-gb274808
2024-01-29T16:01:02.685972Z DEBUG find_pointers{base=0x6ea0000 size=19234816}: bxt_rs::utils::pointer: 0x6ea8e70: build_number
2024-01-29T16:01:02.687986Z DEBUG find_pointers{base=0x6ea0000 size=19234816}: bxt_rs::utils::pointer: 0x6ea18a0: _ZN7CBaseUI10HideGameUIEv
2024-01-29T16:01:02.688285Z DEBUG find_pointers{base=0x6ea0000 size=19234816}: bxt_rs::utils::pointer: MISSING: Cbuf_AddFilteredText
2024-01-29T16:01:02.688483Z DEBUG find_pointers{base=0x6ea0000 size=19234816}: bxt_rs::utils::pointer: 0x6ec6d60: Cbuf_AddText
2024-01-29T16:01:02.688711Z DEBUG find_pointers{base=0x6ea0000 size=19234816}: bxt_rs::utils::pointer: MISSING: Cbuf_AddTextToBuffer
2024-01-29T16:01:02.688907Z DEBUG find_pointers{base=0x6ea0000 size=19234816}: bxt_rs::utils::pointer: 0x6ec6db0: Cbuf_InsertText
2024-01-29T16:01:02.689142Z DEBUG find_pointers{base=0x6ea0000 size=19234816}: bxt_rs::utils::pointer: 0x6eb7470: CL_Disconnect
2024-01-29T16:01:02.689371Z DEBUG find_pointers{base=0x6ea0000 size=19234816}: bxt_rs::utils::pointer: 0x80cf540: cl_funcs
2024-01-29T16:01:02.689536Z DEBUG find_pointers{base=0x6ea0000 size=19234816}: bxt_rs::utils::pointer: 0x6eb96e0: CL_GameDir_f
2024-01-29T16:01:02.689728Z DEBUG find_pointers{base=0x6ea0000 size=19234816}: bxt_rs::utils::pointer: 0x6eb8bd0: CL_Move
2024-01-29T16:01:02.689897Z DEBUG find_pointers{base=0x6ea0000 size=19234816}: bxt_rs::utils::pointer: 0x6eb034d: CL_PlayDemo_f
2024-01-29T16:01:02.690091Z DEBUG find_pointers{base=0x6ea0000 size=19234816}: bxt_rs::utils::pointer: 0x6eb067d: CL_ViewDemo_f
2024-01-29T16:01:02.690265Z DEBUG find_pointers{base=0x6ea0000 size=19234816}: bxt_rs::utils::pointer: 0x6eab0b0: ClientDLL_Init
2024-01-29T16:01:02.690446Z DEBUG find_pointers{base=0x6ea0000 size=19234816}: bxt_rs::utils::pointer: 0x6eab9e0: ClientDLL_DrawTransparentTriangles
2024-01-29T16:01:02.690646Z DEBUG find_pointers{base=0x6ea0000 size=19234816}: bxt_rs::utils::pointer: MISSING: cl
2024-01-29T16:01:02.690838Z DEBUG find_pointers{base=0x6ea0000 size=19234816}: bxt_rs::utils::pointer: 0x7f278ec: cl_stats
2024-01-29T16:01:02.691043Z DEBUG find_pointers{base=0x6ea0000 size=19234816}: bxt_rs::utils::pointer: 0x80a02c0: cl_viewent
2024-01-29T16:01:02.691267Z DEBUG find_pointers{base=0x6ea0000 size=19234816}: bxt_rs::utils::pointer: 0x80a0e08: cl_viewent_viewmodel
2024-01-29T16:01:02.691472Z DEBUG find_pointers{base=0x6ea0000 size=19234816}: bxt_rs::utils::pointer: 0x7ef65c0: cls
2024-01-29T16:01:02.691696Z DEBUG find_pointers{base=0x6ea0000 size=19234816}: bxt_rs::utils::pointer: 0xa52805c7: cls_demoframecount
2024-01-29T16:01:02.691907Z DEBUG find_pointers{base=0x6ea0000 size=19234816}: bxt_rs::utils::pointer: 0x7efa52c: cls_demos
2024-01-29T16:01:02.692113Z DEBUG find_pointers{base=0x6ea0000 size=19234816}: bxt_rs::utils::pointer: 0x6ec7a70: Cmd_AddMallocCommand
2024-01-29T16:01:02.692274Z DEBUG find_pointers{base=0x6ea0000 size=19234816}: bxt_rs::utils::pointer: 0x6ec77b0: Cmd_Argc
2024-01-29T16:01:02.692497Z DEBUG find_pointers{base=0x6ea0000 size=19234816}: bxt_rs::utils::pointer: 0x6ec77c0: Cmd_Argv
2024-01-29T16:01:02.692690Z DEBUG find_pointers{base=0x6ea0000 size=19234816}: bxt_rs::utils::pointer: 0x7180850: cmd_functions
2024-01-29T16:01:02.692883Z DEBUG find_pointers{base=0x6ea0000 size=19234816}: bxt_rs::utils::pointer: 0x6ecc080: Con_Printf
2024-01-29T16:01:02.693051Z DEBUG find_pointers{base=0x6ea0000 size=19234816}: bxt_rs::utils::pointer: 0x6ecbba0: Con_ToggleConsole_f
2024-01-29T16:01:02.693291Z DEBUG find_pointers{base=0x6ea0000 size=19234816}: bxt_rs::utils::pointer: 0x7ea4300: com_gamedir
2024-01-29T16:01:02.693470Z DEBUG find_pointers{base=0x6ea0000 size=19234816}: bxt_rs::utils::pointer: 0x6ecdd80: Cvar_RegisterVariable
2024-01-29T16:01:02.693694Z DEBUG find_pointers{base=0x6ea0000 size=19234816}: bxt_rs::utils::pointer: 0x71921fc: cvar_vars
2024-01-29T16:01:02.693870Z DEBUG find_pointers{base=0x6ea0000 size=19234816}: bxt_rs::utils::pointer: 0x6eb1390: DrawCrosshair
2024-01-29T16:01:02.694084Z DEBUG find_pointers{base=0x6ea0000 size=19234816}: bxt_rs::utils::pointer: 0x6edc8e0: Draw_FillRGBABlend
2024-01-29T16:01:02.694294Z DEBUG find_pointers{base=0x6ea0000 size=19234816}: bxt_rs::utils::pointer: 0x6edb600: Draw_String
2024-01-29T16:01:02.694498Z DEBUG find_pointers{base=0x6ea0000 size=19234816}: bxt_rs::utils::pointer: 0x7009a18: frametime_remainder
2024-01-29T16:01:02.694684Z DEBUG find_pointers{base=0x6ea0000 size=19234816}: bxt_rs::utils::pointer: 0x6eec140: GL_BeginRendering
2024-01-29T16:01:02.694899Z DEBUG find_pointers{base=0x6ea0000 size=19234816}: bxt_rs::utils::pointer: 0x7692620: gEntityInterface
2024-01-29T16:01:02.695081Z DEBUG find_pointers{base=0x6ea0000 size=19234816}: bxt_rs::utils::pointer: 0x74dff44: gLoadSky
2024-01-29T16:01:02.695280Z DEBUG find_pointers{base=0x6ea0000 size=19234816}: bxt_rs::utils::pointer: 0x786bf80: g_svmove
2024-01-29T16:01:02.695445Z DEBUG find_pointers{base=0x6ea0000 size=19234816}: bxt_rs::utils::pointer: 0x6effe90: Key_Event
2024-01-29T16:01:02.695624Z DEBUG find_pointers{base=0x6ea0000 size=19234816}: bxt_rs::utils::pointer: 0x6f491c0: LoadEntityDLLs
2024-01-29T16:01:02.695846Z DEBUG find_pointers{base=0x6ea0000 size=19234816}: bxt_rs::utils::pointer: 0x6ec8270: Mod_LeafPVS
2024-01-29T16:01:02.696036Z DEBUG find_pointers{base=0x6ea0000 size=19234816}: bxt_rs::utils::pointer: 0x6ef5b50: Host_FilterTime
2024-01-29T16:01:02.696219Z DEBUG find_pointers{base=0x6ea0000 size=19234816}: bxt_rs::utils::pointer: 0x7954028: host_frametime
2024-01-29T16:01:02.696396Z DEBUG find_pointers{base=0x6ea0000 size=19234816}: bxt_rs::utils::pointer: 0x6ef6d80: Host_InitializeGameDLL
2024-01-29T16:01:02.696560Z DEBUG find_pointers{base=0x6ea0000 size=19234816}: bxt_rs::utils::pointer: 0x6efb8c0: Host_NextDemo
2024-01-29T16:01:02.696726Z DEBUG find_pointers{base=0x6ea0000 size=19234816}: bxt_rs::utils::pointer: 0x6ef6c00: Host_Shutdown
2024-01-29T16:01:02.696914Z DEBUG find_pointers{base=0x6ea0000 size=19234816}: bxt_rs::utils::pointer: 0x6efb2e0: Host_Tell_f
2024-01-29T16:01:02.697071Z DEBUG find_pointers{base=0x6ea0000 size=19234816}: bxt_rs::utils::pointer: 0x6ef8c10: Host_ValidSave
2024-01-29T16:01:02.697291Z DEBUG find_pointers{base=0x6ea0000 size=19234816}: bxt_rs::utils::pointer: 0x6eaa810: hudGetScreenInfo
2024-01-29T16:01:02.697486Z DEBUG find_pointers{base=0x6ea0000 size=19234816}: bxt_rs::utils::pointer: 0x6eac200: hudGetViewAngles
2024-01-29T16:01:02.697649Z DEBUG find_pointers{base=0x6ea0000 size=19234816}: bxt_rs::utils::pointer: 0x74f52f8: idum
2024-01-29T16:01:02.697838Z DEBUG find_pointers{base=0x6ea0000 size=19234816}: bxt_rs::utils::pointer: 0x792f100: movevars
2024-01-29T16:01:02.698048Z DEBUG find_pointers{base=0x6ea0000 size=19234816}: bxt_rs::utils::pointer: 0x6f66620: Memory_Init
2024-01-29T16:01:02.698254Z DEBUG find_pointers{base=0x6ea0000 size=19234816}: bxt_rs::utils::pointer: 0x6fa4ffd: Mem_Free
2024-01-29T16:01:02.698478Z DEBUG find_pointers{base=0x6ea0000 size=19234816}: bxt_rs::utils::pointer: 0x78c1720: paintbuffer
2024-01-29T16:01:02.698643Z DEBUG find_pointers{base=0x6ea0000 size=19234816}: bxt_rs::utils::pointer: 0x78cb860: paintedtime
2024-01-29T16:01:02.698846Z DEBUG find_pointers{base=0x6ea0000 size=19234816}: bxt_rs::utils::pointer: 0x74f4a70: pmove
2024-01-29T16:01:02.699005Z DEBUG find_pointers{base=0x6ea0000 size=19234816}: bxt_rs::utils::pointer: 0x6f0ee20: ran1
2024-01-29T16:01:02.699167Z DEBUG find_pointers{base=0x6ea0000 size=19234816}: bxt_rs::utils::pointer: 0x74f52fc: ran1::iy
2024-01-29T16:01:02.699343Z DEBUG find_pointers{base=0x6ea0000 size=19234816}: bxt_rs::utils::pointer: 0x74f4b20: ran1::iv
2024-01-29T16:01:02.699524Z DEBUG find_pointers{base=0x6ea0000 size=19234816}: bxt_rs::utils::pointer: 0x7954100: realtime
2024-01-29T16:01:02.699741Z DEBUG find_pointers{base=0x6ea0000 size=19234816}: bxt_rs::utils::pointer: MISSING: r_refdef
2024-01-29T16:01:02.699941Z DEBUG find_pointers{base=0x6ea0000 size=19234816}: bxt_rs::utils::pointer: 0x7d66250: r_refdef_vieworg
2024-01-29T16:01:02.700120Z DEBUG find_pointers{base=0x6ea0000 size=19234816}: bxt_rs::utils::pointer: 0x7d6625c: r_refdef_viewangles
2024-01-29T16:01:02.700276Z DEBUG find_pointers{base=0x6ea0000 size=19234816}: bxt_rs::utils::pointer: 0x6ee52e0: R_RenderView
2024-01-29T16:01:02.700436Z DEBUG find_pointers{base=0x6ea0000 size=19234816}: bxt_rs::utils::pointer: 0x6ee4160: R_SetFrustum
2024-01-29T16:01:02.700593Z DEBUG find_pointers{base=0x6ea0000 size=19234816}: bxt_rs::utils::pointer: 0x6f49700: ReleaseEntityDlls
2024-01-29T16:01:02.700806Z DEBUG find_pointers{base=0x6ea0000 size=19234816}: bxt_rs::utils::pointer: 0x6ee4bb0: R_Clear
2024-01-29T16:01:02.701010Z DEBUG find_pointers{base=0x6ea0000 size=19234816}: bxt_rs::utils::pointer: 0x6ee6790: R_DrawSequentialPoly
2024-01-29T16:01:02.701162Z DEBUG find_pointers{base=0x6ea0000 size=19234816}: bxt_rs::utils::pointer: 0x6eef55e: R_DrawSkyBox
2024-01-29T16:01:02.701334Z DEBUG find_pointers{base=0x6ea0000 size=19234816}: bxt_rs::utils::pointer: 0x6ee3990: R_DrawViewModel
2024-01-29T16:01:02.701508Z DEBUG find_pointers{base=0x6ea0000 size=19234816}: bxt_rs::utils::pointer: 0x6eee772: R_LoadSkys
2024-01-29T16:01:02.701693Z DEBUG find_pointers{base=0x6ea0000 size=19234816}: bxt_rs::utils::pointer: 0x6ee3d30: R_PreDrawViewModel
2024-01-29T16:01:02.701886Z DEBUG find_pointers{base=0x6ea0000 size=19234816}: bxt_rs::utils::pointer: 0x6f2cd60: S_PaintChannels
2024-01-29T16:01:02.702065Z DEBUG find_pointers{base=0x6ea0000 size=19234816}: bxt_rs::utils::pointer: 0x6f2c6a0: S_TransferStereo16
2024-01-29T16:01:02.702220Z DEBUG find_pointers{base=0x6ea0000 size=19234816}: bxt_rs::utils::pointer: 0x6eeadc0: SCR_DrawLoading
2024-01-29T16:01:02.702421Z DEBUG find_pointers{base=0x6ea0000 size=19234816}: bxt_rs::utils::pointer: 0x6fe4a8c: scr_fov_value
2024-01-29T16:01:02.702635Z DEBUG find_pointers{base=0x6ea0000 size=19234816}: bxt_rs::utils::pointer: 0x7557cd8: shm
2024-01-29T16:01:02.702806Z DEBUG find_pointers{base=0x6ea0000 size=19234816}: bxt_rs::utils::pointer: 0x76a4c00: sv
2024-01-29T16:01:02.703012Z DEBUG find_pointers{base=0x6ea0000 size=19234816}: bxt_rs::utils::pointer: 0x76a4080: svs
2024-01-29T16:01:02.703170Z DEBUG find_pointers{base=0x6ea0000 size=19234816}: bxt_rs::utils::pointer: 0x76861e0: sv_areanodes
2024-01-29T16:01:02.703398Z DEBUG find_pointers{base=0x6ea0000 size=19234816}: bxt_rs::utils::pointer: 0x6f453e0: SV_AddLinksToPM
2024-01-29T16:01:02.703597Z DEBUG find_pointers{base=0x6ea0000 size=19234816}: bxt_rs::utils::pointer: 0x6f450e0: SV_AddLinksToPM_
2024-01-29T16:01:02.703765Z DEBUG find_pointers{base=0x6ea0000 size=19234816}: bxt_rs::utils::pointer: 0x6f47d1f: SV_ExecuteClientMessage
2024-01-29T16:01:02.703930Z DEBUG find_pointers{base=0x6ea0000 size=19234816}: bxt_rs::utils::pointer: 0x6f3c0f0: SV_Frame
2024-01-29T16:01:02.704120Z DEBUG find_pointers{base=0x6ea0000 size=19234816}: bxt_rs::utils::pointer: 0x6f457e0: SV_RunCmd
2024-01-29T16:01:02.704272Z DEBUG find_pointers{base=0x6ea0000 size=19234816}: bxt_rs::utils::pointer: 0x6f49b30: _Z18Sys_VID_FlipScreenv
2024-01-29T16:01:02.704497Z DEBUG find_pointers{base=0x6ea0000 size=19234816}: bxt_rs::utils::pointer: MISSING: _Z18Sys_VID_FlipScreenv_old
2024-01-29T16:01:02.704703Z DEBUG find_pointers{base=0x6ea0000 size=19234816}: bxt_rs::utils::pointer: 0x6ff0578: tri
2024-01-29T16:01:02.704894Z DEBUG find_pointers{base=0x6ea0000 size=19234816}: bxt_rs::utils::pointer: 0x6f60150: V_ApplyShake
2024-01-29T16:01:02.705048Z DEBUG find_pointers{base=0x6ea0000 size=19234816}: bxt_rs::utils::pointer: 0x6f603c0: V_FadeAlpha
2024-01-29T16:01:02.705202Z DEBUG find_pointers{base=0x6ea0000 size=19234816}: bxt_rs::utils::pointer: 0x6f5fc30: V_RenderView
2024-01-29T16:01:02.705357Z DEBUG find_pointers{base=0x6ea0000 size=19234816}: bxt_rs::utils::pointer: 0x6f4cc70: VideoMode_IsWindowed
2024-01-29T16:01:02.705552Z DEBUG find_pointers{base=0x6ea0000 size=19234816}: bxt_rs::utils::pointer: 0x6f4cb80: VideoMode_GetCurrentVideoMode
2024-01-29T16:01:02.705759Z DEBUG find_pointers{base=0x6ea0000 size=19234816}: bxt_rs::utils::pointer: 0x7954220: window_rect
2024-01-29T16:01:02.705934Z DEBUG find_pointers{base=0x6ea0000 size=19234816}: bxt_rs::utils::pointer: 0x6f65750: Z_Free
2024-01-29T16:01:02.706188Z DEBUG find_pointers{base=0x6ea0000 size=19234816}: bxt_rs::hooks::engine: Some(19356): client_s_edict_offset
2024-01-29T16:01:04.675869Z DEBUG sdl::find_pointers: bxt_rs::utils::pointer: 0x816e990: SDL_GetMouseState
2024-01-29T16:01:04.676158Z DEBUG sdl::find_pointers: bxt_rs::utils::pointer: 0x817e090: SDL_GL_ExtensionSupported
2024-01-29T16:01:04.676368Z DEBUG sdl::find_pointers: bxt_rs::utils::pointer: 0x817dff0: SDL_GL_GetProcAddress
2024-01-29T16:01:04.676566Z DEBUG sdl::find_pointers: bxt_rs::utils::pointer: 0x816f0b0: SDL_SetRelativeMouseMode
2024-01-29T16:01:04.676730Z DEBUG sdl::find_pointers: bxt_rs::utils::pointer: 0x816f060: SDL_WarpMouseInWindow
2024-01-29T16:01:04.676852Z DEBUG sdl::find_pointers: bxt_rs::utils::pointer: 0x81676d0: SDL_WaitEventTimeout
2024-01-29T16:01:04.752944Z  WARN sdl::find_pointers:gl::find_pointers: bxt_rs::modules::capture: MISSING: GL_EXT_memory_object OpenGL extension
2024-01-29T16:01:04.753292Z  WARN sdl::find_pointers:gl::find_pointers: bxt_rs::modules::capture: MISSING: GL_EXT_memory_object_win32 OpenGL extension
2024-01-29T16:01:04.753631Z  WARN sdl::find_pointers:gl::find_pointers: bxt_rs::modules::capture: MISSING: GL_EXT_semaphore OpenGL extension
2024-01-29T16:01:04.753881Z  WARN sdl::find_pointers:gl::find_pointers: bxt_rs::modules::capture: MISSING: GL_EXT_semaphore_win32 OpenGL extension
2024-01-29T16:01:04.754553Z DEBUG opengl32::find_pointers: bxt_rs::utils::pointer: 0x7a8c7620: wglGetCurrentContext
2024-01-29T16:01:04.754807Z DEBUG opengl32::find_pointers: bxt_rs::utils::pointer: 0x7a8c8160: wglGetProcAddress
2024-01-29T16:01:04.755377Z DEBUG bxt::find_pointers: bxt_rs::utils::pointer: 0x15d3f31c: bxt_on_tas_playback_frame
2024-01-29T16:01:04.755633Z DEBUG bxt::find_pointers: bxt_rs::utils::pointer: 0x15d3f318: bxt_on_tas_playback_stopped
2024-01-29T16:01:04.755799Z DEBUG bxt::find_pointers: bxt_rs::utils::pointer: 0x15c69a10: bxt_simulation_ipc_is_client_initialized
2024-01-29T16:01:04.755967Z DEBUG bxt::find_pointers: bxt_rs::utils::pointer: 0x15bef910: bxt_tas_load_script_from_string
2024-01-29T16:01:04.756139Z DEBUG bxt::find_pointers: bxt_rs::utils::pointer: 0x15befa00: bxt_is_tas_editor_active
2024-01-29T16:01:04.756371Z DEBUG bxt::find_pointers: bxt_rs::utils::pointer: 0x15be9b50: bxt_tas_new
2024-01-29T16:01:04.756628Z DEBUG bxt::find_pointers: bxt_rs::utils::pointer: MISSING: bxt_tas_norefresh_until_last_frames
2024-01-29T16:01:04.756806Z DEBUG bxt::find_pointers: bxt_rs::utils::pointer: MISSING: bxt_tas_studio_norefresh_override
2024-01-29T16:01:05.064212Z DEBUG bxt_rs::utils::pointer: 0x376174d0: HudInitFunc
2024-01-29T16:01:05.064358Z DEBUG bxt_rs::utils::pointer: 0x376174b0: HudVidInitFunc
2024-01-29T16:01:05.064520Z DEBUG bxt_rs::utils::pointer: 0x376174f0: HudRedrawFunc
2024-01-29T16:01:05.064668Z DEBUG bxt_rs::utils::pointer: 0x37617510: HudUpdateClientDataFunc
2024-01-29T16:01:05.064828Z DEBUG bxt_rs::utils::pointer: 0x3763d2a0: CalcRefdef
2024-01-29T16:01:05.064936Z DEBUG bxt_rs::utils::pointer: 0x3761e6e0: IN_ActivateMouse
2024-01-29T16:01:05.065024Z DEBUG bxt_rs::utils::pointer: 0x3761e720: IN_DeactivateMouse
2024-01-29T16:01:05.065118Z DEBUG bxt_rs::utils::pointer: 0x376298c0: DrawTransparentTriangles
2024-01-29T16:01:05.065259Z DEBUG bxt_rs::utils::pointer: 0x37611700: PostRunCmd
2024-01-29T16:01:05.065367Z DEBUG bxt_rs::utils::pointer: 0x3761e690: Shutdown
2024-01-29T16:01:54.243094Z DEBUG bxt_rs::modules::demo_playback: Demo filename: "test_13"
2024-01-29T16:01:54.243976Z DEBUG bxt_rs::modules::demo_playback: Demo filename: "test_12"
2024-01-29T16:01:54.244115Z DEBUG bxt_rs::modules::demo_playback: Demo filename: "test_11"
2024-01-29T16:01:54.244224Z DEBUG bxt_rs::modules::demo_playback: Demo filename: "test_10"
2024-01-29T16:01:54.244342Z DEBUG bxt_rs::modules::demo_playback: Demo filename: "test_9"
2024-01-29T16:01:54.244461Z DEBUG bxt_rs::modules::demo_playback: Demo filename: "test_8"
2024-01-29T16:01:54.244583Z DEBUG bxt_rs::modules::demo_playback: Demo filename: "test_7"
2024-01-29T16:01:54.244684Z DEBUG bxt_rs::modules::demo_playback: Demo filename: "test_6"
2024-01-29T16:01:54.244787Z DEBUG bxt_rs::modules::demo_playback: Demo filename: "test_5"
2024-01-29T16:01:54.244901Z DEBUG bxt_rs::modules::demo_playback: Demo filename: "test_4"
2024-01-29T16:01:54.245002Z DEBUG bxt_rs::modules::demo_playback: Demo filename: "test_3"
2024-01-29T16:01:54.245102Z DEBUG bxt_rs::modules::demo_playback: Demo filename: "test_2"
2024-01-29T16:01:54.245195Z DEBUG bxt_rs::modules::demo_playback: Demo filename: "test_1"
```

**Comment by khanghugo** [comment]
Hey, have you resolved this? This still seems to behave normally for me.

**Comment by sykesjd** [comment]
No, I have not resolved this. I am still waiting for additional guidance on how to debug this further.
